# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - lmsdevapi2

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://lmsregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_138d786de75d4a8aaa28067131a47245 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d9ea53a9c08647a09587067924ac1bf6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: lmsregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_138d786de75d4a8aaa28067131a47245 }}/lmspublicapi1:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lmsdevapi2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e5c392cd55d2418da3360e93f546c610 }}
        images: 'lmsregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_138d786de75d4a8aaa28067131a47245 }}/lmspublicapi1:${{ github.sha }}'